# Generated by Django 4.2.9 on 2024-01-26 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogarticles_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 16, 27, 0, 944785, tzinfo=datetime.timezone.utc)),
        ),
    ]
