# Generated by Django 4.2.9 on 2024-01-25 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_articlepost_created_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 8, 24, 8, 915598, tzinfo=datetime.timezone.utc)),
        ),
    ]
