# Generated by Django 4.2.9 on 2024-01-27 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_alter_articlepost_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 27, 6, 3, 38, 362966, tzinfo=datetime.timezone.utc)),
        ),
    ]
