# Generated by Django 4.2.9 on 2024-01-26 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_articlecolumn_user_alter_articlepost_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 8, 47, 46, 145436, tzinfo=datetime.timezone.utc)),
        ),
    ]
