# Generated by Django 4.2.9 on 2024-01-23 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogarticles_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogarticles',
            options={'ordering': ('publish',)},
        ),
        migrations.AlterField(
            model_name='blogarticles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 3, 37, 39, 488903, tzinfo=datetime.timezone.utc)),
        ),
    ]
