# Generated by Django 4.2.9 on 2024-01-24 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogarticles_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 14, 13, 4, 704827, tzinfo=datetime.timezone.utc)),
        ),
    ]
