# Generated by Django 4.2.9 on 2024-01-26 01:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogarticles_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 1, 44, 24, 519928, tzinfo=datetime.timezone.utc)),
        ),
    ]
