# Generated by Django 4.2.9 on 2024-01-26 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogarticles_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 8, 47, 46, 133694, tzinfo=datetime.timezone.utc)),
        ),
    ]
