# Generated by Django 4.2.9 on 2024-01-26 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogarticles_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 16, 25, 29, 97941, tzinfo=datetime.timezone.utc)),
        ),
    ]
